simple version (#1)
* move to workspaces

* move tsconfig

* fix example

* add simple version

* ci

* ci

* fix build

* hmm

* expect to fail

* update readme

* replace with map

* fix typo

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -20,4 +20,11 @@ jobs:
         run: bun install --frozen-lockfile
       - name: Build
         run: bun run build
+        working-directory: packages/next-broken-links
+      - name: Build example
+        run: bun run build
+        working-directory: examples/static-export
+      - name: Check links
+        # expect to fail
+        run: (bun run ../../packages/next-broken-links/dist/index.js && exit 1) || exit 0
         working-directory: examples/static-export
