expect to fail

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -24,3 +24,7 @@ jobs:
       - name: Build example
         run: bun run build
         working-directory: examples/static-export
+      - name: Check links
+        # expect to fail
+        run: (bun run ../../packages/next-broken-links/dist/index.js && exit 1) || exit 0
+        working-directory: examples/static-export
